### PR TITLE
added prices for items and wiki look-up

### PR DESCRIPTION
**Pull request by greatmoves**

### CODE REVIEW

**Comment by botanicvelious** [comment]
I don't have the ability to test the code however it seemed ok, you were able to test it correct? If so I can merge it.

**Comment by greatmoves** [comment]
> 
> 
> I don't have the ability to test the code however it seemed ok, you were able to test it correct? If so I can merge it.

Yea I walked around the G.E looking at people's gear and opening wiki pages for items, and items as members objects on a f2p world. I didn't come across anything going wrong. 
If you have any suggestions for further testing I can do that for you, otherwise it's all good to go.

**Comment by botanicvelious** [comment]
I had to revert this because it caused an error in the build

* What went wrong:
Execution failed for task ':rlpluginEmitManifest'.
> Plugin class "equipmentinspector.EquipmentInspectorPlugin" is not in the output jar

**Comment by botanicvelious** [comment]
https://travis-ci.org/github/runelite/plugin-hub/builds/694452372

**Pull request merged**
